PROFILE_DESCRIPTION="Minimal TLS-only profile for low CPU usage and diagnostics"
NFQWS2_PORTS_TCP=443
NFQWS2_PORTS_UDP=
NFQWS2_UDP_PKT_OUT=0
NFQWS2_OPT="
--filter-tcp=443 --filter-l7=tls <HOSTLIST> --payload=tls_client_hello --lua-desync=fake:blob=fake_default_tls:tcp_md5:tcp_seq=-10000 --lua-desync=multisplit:pos=1,midsld
"
